name: Checkout
on: [push]

jobs:
    checkout-repo:
        runs-on: ubuntu-latest
        steps:
            - name: List Files Before
              run: ls -la
            - uses: actions/checkout@v3
            - name: List files after
              run: ls -la
